### ISSUE TITLE
Spaces in types in template tests, typedefs and template tests

### ISSUE THREAD

**Issue by aschet** [etas/vs-boost-unit-test-adapter#120]
It would be great if the test adapter could support template types that contain spaces e.g. unsigned char. Boost Tests supports selecting such tests since version 1.60. Special characters are replaced by underlines e.g. unsigned_char.

Furthermore there is an issue with typedefs and template tests. The adapter and the test runner "see" the types differently in this scenario. For example: typedef unsigned char byte. The adapter does list it as byte, the Boost test runner as unsigned_char. As a result of this the test can't be executed via the Text Explorer.

**Comment by netspiri** [comment]
Hi @aschet,

Thank you for your interest in the project. This issue has been fixed with recent pull-requests when we introduced `--list_content=DOT` support. Template tests are listed as identified within the Boost Test runner (i.e. using underscores instead of spaces and typedefs are resolved accordingly).

What I would recommend is to try the current (in-development v1.0.7) version (available via the appveyor badge). This makes use of a new discovery technique which should, hopefully, address your issue.

[![Build status](https://ci.appveyor.com/api/projects/status/28lw0jb0k19ekmtq/branch/master?svg=true)](https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter/branch/master)

**Comment by aschet** [comment]
Thanks for the update. I did test the Boost Unit Test Adapter release build 1.0.7.41 (from master) in combination with Visual Studio 2015 Update 2 and Boost 1.60 with this sample code: [TemplateTestExample.txt](https://github.com/etas/vs-boost-unit-test-adapter/files/262174/TemplateTestExample.txt) Unfortunately the issues are still there, all tests of the sample code will be skipped.

**Comment by netspiri** [comment]
Thanks for the sample test. Will investigate this further.

**Comment by netspiri** [comment]
Hi @aschet,

Tried out your test and I did manage to correctly discover all tests and execute them:

![discovery](https://cloud.githubusercontent.com/assets/6962427/15390366/d03b41a6-1dbb-11e6-9040-91681515b1e4.png)

I simply created an empty Visual C++ project which compiles to an executable, added the include directories for Boost (v1.59) includes and library paths, added the source file you provided and discovery was OK when compiling in debug mode. This was tested using the latest master version of the adapter.

At this point, I recommend looking at the 'Tests' section in the output window for any hints. The following is the output from the discovery phase on my environment:

![output](https://cloud.githubusercontent.com/assets/6962427/15390367/d0650dec-1dbb-11e6-86dd-bfa6f2f1aeb4.png)

Things to note: `Discovering (ListContentDiscoverer)`.
If this is not available, or instead you notice `Discovering (SourceCodeDiscoverer)`, this means that list content discovery is not available on your test module. This can be a product of not providing debug symbols or incorrect test adapter configuration. Please note that as a safety measure, we do not execute test modules which we cannot inspect their debug symbols due to a possibility of executing malicious content. Otherwise, consider looking into the wiki at how to override this behaviour.

Should you require further assistance, let us know.

**Comment by aschet** [comment]
Thank you for further clarification. My issue does indeed correspond to the debug symbols. I did further testing and noticed the following behaviour:

- Boost 1.59 with "Generate Debug Info" set to "yes" or "Optimize for debugging (/DEBUG)" -> works as intended
- Boost 1.59 with "Generate Debug Info" set to "Optimize for faster linking (/DEBUG:FASTLINK)" -> tests will be skipped
- Boost 1.60 wither either of the previous configurations -> tests will be skipped

In my real work environment I use the platform toolset of Visual Studio 2010 within Visual Studio 2015. In this configuration the tests will also not be discovered correctly (e.g. unsiged char instead of unsigned_char).

Using the option ForceListContent via .runsettings does resolve this. I am curious which malicious behaviour you try to prevent since all tests except the ones in my sample can be executed anyway when the debug symbols are not there.

It would be great if you could include a message in the "Test" section in the output window that states the fact that either the debug symbols should be activated or the ForceListContent should be set to true via a .runsettings file in case the debug symbols are not available. Since all tests are discovered, ignoring the fact that the debug symbols are available or not, it is not obvious that the Boost Unit Test Adapter can execute some tests and will skip the ones in my sample.

**Comment by netspiri** [comment]
Hi @aschet,

Thank you for your detailed explanation. Will try further tests with Boost 1.60 and different compiler/linker options and version.

In the mean time, please refer to issue #88 as to why we make use of debug symbols - essentially, Visual Studio notifies us of each executable once compiled within a solution, being a test project or otherwise so we need to be careful when executing unknown exectuables.

**Comment by netspiri** [comment]
Hi @aschet,

PR #124 should address some of your mentioned issues. I am not considering it as a final fix at this moment because I think it is best to take this opportunity and discuss alternatives to debug symbols.

I am considering parsing the `.exe` file and trying to identify any Boost strings. This should work for both configurations which do not export debug symbols but I am afraid that this might be slower than looking up debug symbols from within an indexed file.

Any opinions are welcome.

**Comment by aschet** [comment]
Thanks for the ongoing and very responsive support!

**Comment by guwirth** [comment]
@aschet I close this one. Please try again and create for remaining issues a new one.
